/**
 * Russian
 *
 * LCD Menu Messages
 * See also documentation/LCDLanguageFont.md
 *
 */
#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define MAPPER_D0D1                // For Cyrillic
// Define SIMULATE_ROMFONT to see what is seen on the character based display defined in Configuration.h
//#define SIMULATE_ROMFONT
#define DISPLAY_CHARSET_ISO10646_5

#define WELCOME_MSG                         MACHINE_NAME " ?????."
#define MSG_SD_INSERTED                     "????? ?????????"
#define MSG_SD_REMOVED                      "????? ?????????"
#define MSG_MAIN                            "????"
#define MSG_AUTOSTART                       "?????????"
#define MSG_DISABLE_STEPPERS                "????. ?????????"
#define MSG_AUTO_HOME                       "????????"
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "????????? ????"
#define MSG_PREHEAT_PLA                     "?????????? PLA"
#define MSG_PREHEAT_PLA_N                   "?????????? PLA"
#define MSG_PREHEAT_PLA_ALL                 "???????. PLA ???"
#define MSG_PREHEAT_PLA_BEDONLY             "????. PLA ???????"
#define MSG_PREHEAT_PLA_SETTINGS            "????????? PLA"
#define MSG_PREHEAT_ABS                     "?????????? ABS"
#define MSG_PREHEAT_ABS_N                   "?????????? ABS"
#define MSG_PREHEAT_ABS_ALL                 "???????. ABS ??? "
#define MSG_PREHEAT_ABS_BEDONLY             "????. ABS ???????"
#define MSG_PREHEAT_ABS_SETTINGS            "????????? ABS"
#define MSG_COOLDOWN                        "??????????"
#define MSG_SWITCH_PS_ON                    "Switch Power On"
#define MSG_SWITCH_PS_OFF                   "Switch Power Off"
#define MSG_EXTRUDE                         "?????????"
#define MSG_RETRACT                         "?????"
#define MSG_MOVE_AXIS                       "???????? ?? ????"
#define MSG_MOVE_X                          "Move X"
#define MSG_MOVE_Y                          "Move Y"
#define MSG_MOVE_Z                          "Move Z"
#define MSG_MOVE_E                          "Extruder"
#define MSG_MOVE_01MM                       "Move 0.1mm"
#define MSG_MOVE_1MM                        "Move 1mm"
#define MSG_MOVE_10MM                       "Move 10mm"
#define MSG_SPEED                           "????????"
#define MSG_NOZZLE                          LCD_STR_THERMOMETER " ???????"
#define MSG_BED                             LCD_STR_THERMOMETER " ???????"
#define MSG_FAN_SPEED                       "??????"
#define MSG_FLOW                            "?????"
#define MSG_CONTROL                         "?????????"
#define MSG_MIN                             LCD_STR_THERMOMETER " ???????"
#define MSG_MAX                             LCD_STR_THERMOMETER " ????????"
#define MSG_FACTOR                          LCD_STR_THERMOMETER " ??????"
#define MSG_AUTOTEMP                        "Autotemp"
#define MSG_ON                              "???. "
#define MSG_OFF                             "????. "
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_ACC                             "Acc"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "x"
#define MSG_Y                               "y"
#define MSG_Z                               "z"
#define MSG_E                               "e"
#define MSG_VMIN                            "Vmin"
#define MSG_VTRAV_MIN                       "VTrav min"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-retract"
#define MSG_XSTEPS                          "X ???/mm"
#define MSG_YSTEPS                          "Y ???/mm"
#define MSG_ZSTEPS                          "Z ???/mm"
#define MSG_ESTEPS                          "E ???/mm"
#define MSG_TEMPERATURE                     "???????????"
#define MSG_MOTION                          "????????"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		          "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Fil. Dia. 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Fil. Dia. 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Fil. Dia. 3"
#define MSG_CONTRAST                        "LCD contrast"
#define MSG_STORE_EPROM                     "????????? ? EPROM"
#define MSG_LOAD_EPROM                      "??????. ?? EPROM"
#define MSG_RESTORE_FAILSAFE                "????? ????????"
#define MSG_REFRESH                         LCD_STR_REFRESH "????????"
#define MSG_WATCH                           "?????"
#define MSG_PREPARE                         "????????"
#define MSG_TUNE                            "?????????"
#define MSG_PAUSE_PRINT                     "?????????? ??????"
#define MSG_RESUME_PRINT                    "??????. ??????"
#define MSG_STOP_PRINT                      "?????????? ??????"
#define MSG_CARD_MENU                       "???? ?????"
#define MSG_NO_CARD                         "??? ?????"
#define MSG_DWELL                           "???..."
#define MSG_USERWAIT                        "?????????"
#define MSG_RESUMING                        "Resuming print"
#define MSG_PRINT_ABORTED                   "Print aborted"
#define MSG_NO_MOVE                         "??? ????????."
#define MSG_KILLED                          "?????."
#define MSG_STOPPED                         "???????????."
#define MSG_CONTROL_RETRACT                 "????? mm"
#define MSG_CONTROL_RETRACT_SWAP            "???? ????? mm"
#define MSG_CONTROL_RETRACTF                "?????  V"
#define MSG_CONTROL_RETRACT_ZLIFT           "?????? mm"
#define MSG_CONTROL_RETRACT_RECOVER         "??????? +mm"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "???? ??????? +mm"
#define MSG_CONTROL_RETRACT_RECOVERF        "???????  V"
#define MSG_AUTORETRACT                     "?????????"
#define MSG_FILAMENTCHANGE                  "Change filament"
#define MSG_INIT_SDCARD                     "Init. SD-Card"
#define MSG_CNG_SDCARD                      "Change SD-Card"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop abort"
#define MSG_END_HOUR                        "hours"
#define MSG_END_MINUTE                      "minutes"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Calibration"
    #define MSG_DELTA_CALIBRATE_X           "Calibrate X"
    #define MSG_DELTA_CALIBRATE_Y           "Calibrate Y"
    #define MSG_DELTA_CALIBRATE_Z           "Calibrate Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_RU_H
